spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
file.upload-dir=${FILE_UPLOAD_DIR:uploads}
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
jwt.secret=${JWT_SECRET}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
